# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
 name: Azure Pipelines
 vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarQubePrepare@7
  inputs:
    SonarQube: sonarqube
    scannerMode: dotnet
    projectKey: RSDocs
    extraProperties: |
     sonar.scanner.skipJreProvisioning=true

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: SonarQubeAnalyze@7

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'